### ISSUE TITLE
open web not working

### ISSUE THREAD

**Issue by NovellDevelopment** [spacebarchat/client#123]
Hi, i have done everything right to get server and client run. Server runs all good, and client build etc works BUT when i press W on cmd that should open web, cmd just crash with error and i dont know what to do anymore, i have tried to fix it, but still broken.

ERROR:

› Open in the web browser...
› Press ? │ show all commands
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\MYACCOUNT\fosscord-client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\MYACCOUNT\fosscord-client\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\MYACCOUNT\fosscord-client\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\MYACCOUNT\fosscord-client\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\MYACCOUNT\fosscord-client\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\MYACCOUNT\fosscord-client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\MYACCOUNT\fosscord-client\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\MYACCOUNT\fosscord-client\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\MYACCOUNT\fosscord-client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\MYACCOUNT\fosscord-client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\MYACCOUNT\fosscord-client\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by MaddyUnderStars** [comment]
See the answers to this question: https://stackoverflow.com/questions/69962209/what-is-openssl-legacy-provider-in-node-js-v17

**Comment by Puyodead1** [comment]
~~Master branch isn’t being worked on anymore, I suggest using the dev/bare-rewrite branch~~

Edit: at the time of edit, dev/bare-rewrite is now master
